on:
  push:
    branches:
      - frontend
      - backend
  pull_request:
    types: [closed]
    branches:
      - frontend
      - backend

env:
  BACKEND_CONDN: "(github.event_name == 'push' && github.ref == 'refs/heads/backend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/backend')"
  FRONTEND_CONDN: "(github.event_name == 'push' && github.ref == 'refs/heads/frontend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/frontend')"

  FRONTEND_WRK_DIR: "frontend"
  FRONTEND_SRC_DIR: "frontend/dist/*"
  FRONTEND_TMP_DST_DIR: "~/backup/"
  FRONTEND_FINAL_DIR: "~/final-webserver/frontend/"

  BACKEND_WRK_DIR: "backend"
  BACKEND_SRC_DIR: "backend/*"
  BACKEND_TMP_DST_DIR: "~/temp-test/"
  BACKEND_FINAL_DIR: "~/final-webserver/backend/"

  BACKUP_DIR: "~/superadmin-backup/"
  ENV_BACKUP_DIR: "~/env-backup/.env"

jobs:
  back-install-and-build:
    if: |
        (github.event_name == 'push' && github.ref == 'refs/heads/backend') 
        || 
        (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/backend')
    name: Backend Install and Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        php-version: [7.4]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install package using Composer
        working-directory: ${{ env.BACKEND_WRK_DIR }}
        run: |
          composer --version
          #composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          #name: backend-artifact__${{ github.sha }}
          name: backend-artifact--${{ steps.git_commit_hash.outputs.short_commit_hash }}
          path: "${{ env.BACKEND_WRK_DIR }}"
          if-no-files-found: warn
          compression-level: 6
          overwrite: false

      - name: Copy Backend source code
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          source: ${{ env.BACKEND_SRC_DIR }}
          target: ${{ env.BACKEND_TMP_DST_DIR }}
 
  front-install-and-build:
    if: |
            (github.event_name == 'push' && github.ref == 'refs/heads/frontend') 
            || 
            (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/frontend') 
    name: Frontend Install and Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        working-directory: ${{ env.FRONTEND_WRK_DIR }}
        run: |
          npm install
          npm run build
 
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact__${{ github.sha }}
          path: "${{ env.FRONTEND_WRK_DIR }}/dist"
          if-no-files-found: warn
          compression-level: 6
          overwrite: false

      - name: Copy Frontend source code 
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          source: ${{ env.FRONTEND_SRC_DIR }}
          target: ${{ env.FRONTEND_TMP_DST_DIR }}/

  Deploying-Code:
    name: Deploying the code
    runs-on: ubuntu-latest
    needs: 
      - back-install-and-build
      - front-install-and-build
    if: |
      always() &&
      (needs.back-install-and-build.result == 'success' || needs.front-install-and-build.result == 'success') &&
      !(needs.back-install-and-build.result == 'failure' && needs.front-install-and-build.result == 'skipped') &&
      !(needs.front-install-and-build.result == 'failure' && needs.back-install-and-build.result == 'skipped')
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Deploy Backend
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/backend') 
          || 
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/backend')
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            echo "Deploying Backend and Testing!!!"
            mkdir -p  ${{ env.BACKEND_FINAL_DIR }}
            mkdir -p ${{ env.BACKUP_DIR }}/backend__$(date +'%Y-%m-%d')___${{ github.sha }}
            cp -r ${{ env.BACKEND_TMP_DST_DIR }}/${{ env.BACKEND_SRC_DIR }} ${{ env.BACKEND_FINAL_DIR }} || exit 1
            cp -r ${{ env.BACKEND_TMP_DST_DIR }}/${{ env.BACKEND_SRC_DIR }} ${{ env.BACKUP_DIR }}/backend__$(date +'%Y-%m-%d')___${{ github.sha }} || exit 1
            cp -r  ${{ env.ENV_BACKUP_DIR }} ${{ env.BACKEND_FINAL_DIR }} || exit 1
      - name: Deploy Frontend
        if: |
            (github.event_name == 'push' && github.ref == 'refs/heads/frontend') 
            || 
            (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/frontend')
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            echo "Deploying Frontend and Testing!!!"
            
            mkdir -p ${{ env.FRONTEND_FINAL_DIR }}
            mkdir -p ${{ env.BACKUP_DIR }}/frontend__$(date +'%Y-%m-%d')___${{ github.sha }}
            
            cp -r ${{ env.FRONTEND_TMP_DST_DIR }}/${{ env.FRONTEND_SRC_DIR }} ${{ env.FRONTEND_FINAL_DIR }} || exit 1
            cp -r -r ${{ env.FRONTEND_TMP_DST_DIR }}/${{ env.FRONTEND_SRC_DIR }} ${{ env.BACKUP_DIR }}/frontend__$(date +'%Y-%m-%d')___${{ github.sha }} || exit 1

            sudo systemctl stop nginx

            if ! sudo systemctl is-active --quiet nginx; then
              echo "WARNING: Nginx is not running properly after restart!"
              echo "Nginx status:"
              sudo systemctl status nginx
              exit 1
            else
              echo "Nginx restarted successfully and is running."
            fi            