name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - frontend
      - backend

env:
  FRNT_DIR: "environment/dev"
  BACK_DIR: "environment/stage_template_call"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Normal Listing files
        run: |
          ls -al

      - name: Merge Deploy
        if: github.event.pull_request.merged == true
        run: |
          echo "Deploying to ${GITHUB_REF}"
          ls -al

        # FOR REFERENCE TO LOGIN USING SSH https://medium.com/@tcij1013/how-to-use-github-action-to-run-ssh-commands-609df2a88ac3
    - name: lOGIN to ssh server
      if: github.event.pull_request.merged == || true github.event_name == 'push' && github.ref == 'refs/heads/backend'
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRV_KEY }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 30m
        script: | 
          echo "Nice Job backend!!!"

    - name: lOGIN to ssh server
      if: github.event.pull_request.merged == || true github.event_name == 'push' && github.ref == 'refs/heads/frontend'
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRV_KEY }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 30m
        script: | 
          echo "Nice Job Frontend!!!"

