name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - frontend
      - backend

env:
  FRNT_DIR: "environment/dev"
  BACK_DIR: "environment/stage_template_call"

jobs:
  build-and-deploy:
    name: Testing job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Normal Listing files
        run: |
          ls -al

      - name: Merge Deploy
        if: github.event.pull_request.merged == true
        run: |
          echo "Deploying to ${GITHUB_REF}"
          ls -al


