name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - frontend
      - backend

env:
  FRNT_DIR: "environment/dev"
  BACK_DIR: "environment/stage_template_call"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files
        run: ls -al

      - name: Deploy Backend
        if: github.event.pull_request.merged == true && github.ref == 'refs/heads/backend'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            echo "Deploying Backend!!!"

      - name: Deploy Frontend
        if: github.event.pull_request.merged == true && github.ref == 'refs/heads/frontend'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            echo "Deploying Frontend!!!"
