name: CI/CD Pipeline

on:
  push:
    branches:
      - frontend
      - backend
  pull_request:
    types: [closed]
    branches:
      - frontend
      - backend

env:
  FRONTEND_SRC_DIR: "frontend/dist/*"
  FRONTEND_TMP_DST_DIR: "~/temp-test/"
  FRONTEND_FINAL_DIR: "~/final-webserver/frontend/"
  BACKEND_SRC_DIR: "./"
  BACKEND_TMP_DST_DIR: "~/temp-test/"
  BACKEND_FINAL_DIR: "~/final-webserver/backend"

jobs:
  install-and-build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        working-directory: "frontend/"
        run: |
          ls -al
          npm install
          npm run build
          ls -al
          ls -al dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: "frontend/dist"
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
        
      - name: Copy Backend source code
        if: (github.event_name == 'push' && github.ref == 'refs/heads/backend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/backend')
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          source: ${{ env.BACKEND_SRC_DIR }}
          target: ${{ env.BACKEND_TMP_DST_DIR }}

      - name: Copy Frontend source code
        if: (github.event_name == 'push' && github.ref == 'refs/heads/frontend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/frontend')
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          source: ${{ env.FRONTEND_SRC_DIR }}
          target: ${{ env.FRONTEND_TMP_DST_DIR }}

  Deploying-Code:
    name: Deploying the code
    runs-on: ubuntu-latest
    needs: [install-and-build]
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Deploy Backend
        if: (github.event_name == 'push' && github.ref == 'refs/heads/backend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/backend')
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            echo "Deploying Backend!!!"
            #cd ${{ env.BACKEND_DST_DIR }}
            cp ${BACKEND_TMP_DST_DIR}/${BACKEND_SRC_DIR} ${BACKEND_FINAL_DIR}
            ls -al
            #composer install

      - name: Deploy Frontend
        if: (github.event_name == 'push' && github.ref == 'refs/heads/frontend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/frontend')
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            echo "Deploying Frontend and Testing!!!"
            echo "Deploying Backend!!!"
            #cd ${{ env.FRONTEND_DST_DIR }}
            cp ${FRONTEND_TMP_DST_DIR}/${FRONTEND_SRC_DIR} ${FRONTEND_FINAL_DIR}
name: CI/CD Pipeline

on:
  push:
    branches:
      - frontend
      - backend
  pull_request:
    types: [closed]
    branches:
      - frontend
      - backend

env:
  FRONTEND_SRC_DIR: "frontend/dist/*"
  FRONTEND_TMP_DST_DIR: "~/temp-test/"
  FRONTEND_FINAL_DIR: "~/final-webserver/frontend/"
  BACKEND_SRC_DIR: "./"
  BACKEND_TMP_DST_DIR: "~/temp-test/"
  BACKEND_FINAL_DIR: "~/final-webserver/backend"

jobs:
  install-and-build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        working-directory: "frontend/"
        run: |
          ls -al
          npm install
          npm run build
          ls -al
          ls -al dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: "frontend/dist"
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
        
      - name: Copy Backend source code
        if: (github.event_name == 'push' && github.ref == 'refs/heads/backend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/backend')
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          source: ${{ env.BACKEND_SRC_DIR }}
          target: ${{ env.BACKEND_TMP_DST_DIR }}

      - name: Copy Frontend source code
        if: (github.event_name == 'push' && github.ref == 'refs/heads/frontend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/frontend')
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          source: ${{ env.FRONTEND_SRC_DIR }}
          target: ${{ env.FRONTEND_TMP_DST_DIR }}

  Deploying-Code:
    name: Deploying the code
    runs-on: ubuntu-latest
    needs: [install-and-build]
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Deploy Backend
        if: (github.event_name == 'push' && github.ref == 'refs/heads/backend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/backend')
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            echo "Deploying Backend!!!"
            #cd ${{ env.BACKEND_DST_DIR }}
            cp ${BACKEND_TMP_DST_DIR}/${BACKEND_SRC_DIR} ${BACKEND_FINAL_DIR}
            ls -al
            #composer install

      - name: Deploy Frontend
        if: (github.event_name == 'push' && github.ref == 'refs/heads/frontend') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/frontend')
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            echo "Deploying Frontend and Testing!!!"
            echo "Deploying Backend!!!"
            #cd ${{ env.FRONTEND_DST_DIR }}
            cp ${FRONTEND_TMP_DST_DIR}/${FRONTEND_SRC_DIR} ${FRONTEND_FINAL_DIR}
